### ISSUE TITLE
Link to docker compose file not working

### ISSUE THREAD

**Issue by DjAnu** [parksauce/docker_actual-helpers#5]
Can you please post a docker-compose file for this, link you posted in readme isn't working

![image](https://github.com/user-attachments/assets/fc762503-d3bb-480b-b54f-0f5f684e370a)

**Comment by DjAnu** [comment]
Hi I somehow created the container not sure if it's the correct setup. Can you please help me setting it up. Are you available on discord or reddit to chat for a few min ?

**Comment by realjoshparker** [comment]
Hey, thanks for raising this, I updated the readme to point to the correct link. Seems I didn't update it accordingly when I moved the project to this repository. 

That said, what kind of issues are you facing? I'd be happy to help address them if you raise a separate issue. The container itself is fairly simple, its just a wrapper for the helper scripts. You'll just need to ensure all of the required [variables](https://github.com/parksauce/docker_actual-helpers?tab=readme-ov-file#environment-variables) are set and run the container. By default its setup to run the bank sync script but you can change the script either by passing the name of the script as the command for the container or by using the `SCRIPT` environment variable.

Closing this issue since its been addressed
